### ISSUE TITLE
Herjaa, kun ajaa freshinä docker-compose up

### ISSUE THREAD

**Issue by kakkurij** [kakkurij/SaveSailor#45]
`weather_1          | Dropped all weather tables
weather_1          | weather_station table created!
weather_1          | weather_data table created!
database_1         | 2022-03-16 17:48:27.917 UTC [76] ERROR:  relation "rescue_data" does not exist
database_1         | 2022-03-16 17:48:27.917 UTC [76] STATEMENT:  CREATE TABLE rescue_weather(
database_1         |            index BIGINT,
database_1         |            id INTEGER,
database_1         |            PRIMARY KEY (index, id),
database_1         |            FOREIGN KEY (index) REFERENCES RESCUE_DATA(index),
database_1         |            FOREIGN KEY (id) REFERENCES WEATHER_DATA(id)
database_1         |        );
weather_1          | Traceback (most recent call last):
weather_1          |   File "/usr/src/app/fmi_data.py", line 141, in <module>
weather_1          |     setup_weather_database(conn)
weather_1          |   File "/usr/src/app/database_setup.py", line 95, in setup_weather_database
weather_1          |     create_tables(conn)
weather_1          |   File "/usr/src/app/database_setup.py", line 80, in create_tables
weather_1          |     cur.execute('''CREATE TABLE rescue_weather(
weather_1          | psycopg2.errors.UndefinedTable: relation "rescue_data" does not exist`

Koska rescue_data:lla ei ole omaa luontilausetta, vaan se luodaan "on-demand" tyyppisesti samaan aikaan kun tehdään insert, ei onnistu toi Foreign key relaatio.

Lähtökohtaisesti meitä ei kiinnosta noi FK relaatiot, ja ne tehdään muutenki vasta myöhemmässä vaiheessa, joten ne vois ihan suosista ottaa pois.

Jos haluat replikoida ongelman:

1. Hae docker containerir: `docker ps -a`
2. Poista container: `docker rm <container_id>` (savesailor_database) 
3. Hae imaget: `docker images`
4. Poista image: `docker rmi <image_id>` (postgis)
5. Aja: `docker-compose up`

**Comment by kakkurij** [comment]
Ja tosiaan jos tuon docker-compose up ajaa kahteen kertaan, ni tokalla kerralla onnistuu
